### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Javyre** [Snowlabs/Jamyx#4]
The project as it is work very well and I've been using it for a couple years now. There are some minor things i strongly feel the need for though. 

Here's a TODO in no particular order:
- [ ] Update `jack-rs` version
- [ ] Clean up code:
  - [ ] Remove `unwrap()`s and use proper error handling
  - [ ] Remove ugly leftover commented-out code (that's embarrassing)
  - [ ] Review naming/minor design choices
- [ ] Add Regex matching to port names from cfg file if possible
- [ ] Review realtime code for performance
- [ ] Look into making an equalizer (may be a separate project from jamyx)
